#!/bin/bash
# script script1

bname=$(basename "$0")
echo "Major lab 1, L03: bash script named $bname"

echo "Available disk space"
df -h

if [ $# -ne 1 ]
then
  echo "script1: wrong number of command line arguments"
  echo "usage --script1 $bname <dirname>"
  exit 1
fi

dirname="$1"

if [ -d "$dirname" ]
then
  echo "Directory exists"
  if [ "$(ls -A "$dirname")" ]
  then
    echo "Directory exists and is non-empty, emptying it"
    ls "$dirname"
    rm -r "$dirname"/*
  else
    echo "Directory exists and is empty."
  fi
else
  echo "Directory does not exist"
  mkdir "$dirname"
fi

cd "$dirname"

echo "a" > required.file1
echo "b" > required.file2
echo "c" > required.file3